### ISSUE TITLE
Remove reference to paypal?

### ISSUE THREAD

**Issue by otoolec** [xjdr/xio#89]
It looks like there are a couple of references to PayPal in the source and tests.  Should these be removed? 

https://github.com/xjdr/xio/search?utf8=%E2%9C%93&q=paypal

- [.arcconfig] (https://github.com/xjdr/xio/blob/3e4fa84d66066d7a851d3b6862d65a3653d2d218/.arcconfig)
- [XioSecurityHandlerImplTest.java] (https://github.com/xjdr/xio/blob/228365105f2b144301e0f5dfad6dc918c22716f7/src/test/java/com/xjeffrose/xio/SSL/XioSecurityHandlerImplTest.java)
- [XioClientTest.java] (https://github.com/xjdr/xio/blob/95c6d8242350799804e327342cec46e106ec394d/src/test/java/com/xjeffrose/xio/client/XioClientTest.java)
- [XioSecurityHandlerImpl.java] (https://github.com/xjdr/xio/blob/228365105f2b144301e0f5dfad6dc918c22716f7/src/main/java/com/xjeffrose/xio/SSL/XioSecurityHandlerImpl.java)
- [XioServerFunctionalTest.java] (https://github.com/xjdr/xio/blob/228365105f2b144301e0f5dfad6dc918c22716f7/src/test/java/com/xjeffrose/xio/server/XioServerFunctionalTest.java)

**Comment by xjdr** [comment]
I don't have an issue with the tests.

I have removed the arcconfig and changed the self signed cert to reference xjeffrose.com

fixed in commit  [ master 32f28ce ] 

approved - JR

**Comment by otoolec** [comment]
👍
